# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            It's a Blog
tagline:          'In two languages'
description:      'Have you seen enough of these yet?'
baseurl:          /